
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiladorjava.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LITERAL_FLOTANTE = 29;
  public static final int MULTIPLICACION = 16;
  public static final int CLASS = 4;
  public static final int ELSE = 6;
  public static final int INT = 9;
  public static final int PRIVATE = 3;
  public static final int WHILE = 7;
  public static final int DIVISION = 17;
  public static final int SUMA = 14;
  public static final int RETURN = 8;
  public static final int MAYOR_QUE = 21;
  public static final int TRUE = 12;
  public static final int IF = 5;
  public static final int ID = 31;
  public static final int PUBLIC = 2;
  public static final int BOOLEAN = 10;
  public static final int COMA = 23;
  public static final int MENOR_QUE = 20;
  public static final int ASIGNACION = 18;
  public static final int EOF = 0;
  public static final int IGUAL_QUE = 19;
  public static final int LITERAL_ENTERO = 28;
  public static final int FALSE = 13;
  public static final int PARENTESIS_C = 27;
  public static final int error = 1;
  public static final int PARENTESIS_A = 26;
  public static final int LLAVE_C = 25;
  public static final int LLAVE_A = 24;
  public static final int PUNTO_COMA = 22;
  public static final int LITERAL_STRING = 30;
  public static final int VOID = 11;
  public static final int RESTA = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLIC",
  "PRIVATE",
  "CLASS",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "INT",
  "BOOLEAN",
  "VOID",
  "TRUE",
  "FALSE",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "ASIGNACION",
  "IGUAL_QUE",
  "MENOR_QUE",
  "MAYOR_QUE",
  "PUNTO_COMA",
  "COMA",
  "LLAVE_A",
  "LLAVE_C",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "LITERAL_ENTERO",
  "LITERAL_FLOTANTE",
  "LITERAL_STRING",
  "ID"
  };
}

